Controllers/coursesearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
//
using CMS.Constants;
using CMS.Services;
using CMS.Models.A1_DB;
using CMS.Models.B1_View;

namespace CMS.Controllers
{
    [Authorize(Roles = RoleCategoryAssign.Admin + "," + RoleCategoryAssign.Student)]
    public class coursesearchController : Controller
    {
        private readonly CMS_DBContext _context;

        public coursesearchController(CMS_DBContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string deptname,string semname)
        {
            //var courseList = await _context.CourseLists.Include(c => c.Dept).Include(c => c.Sem).FirstOrDefaultAsync(m => m.Dept.DeptCategoryName == deptname && m.Sem.SemCategoryName== semname);
            var courseList = new SearchView
            {
                CourseList_Var = _context.CourseLists.Where(m => m.Dept.DeptCategoryName == deptname && m.Sem.SemCategoryName == semname)
            };

            if(courseList == null)
            {
                TempData["Result_coursesearch_search"] = "Negetive";
                //return RedirectToAction("Index", "coursesearch");
            }
            else
            {
                TempData["Result_coursesearch_search"] = "Positive";
                return View("Index", courseList);
            }
            return View(courseList);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CMS-@ViewData["Title"]</title>
    <style type="text/css">
        /* CSS */

        .sidebar {
            height: 100%;
            width: 350px;
            position: absolute;
            left: 0;
            top: 0;
            padding-top: 40px;
            background-color: lightblue;
        }

            .sidebar div {
                padding: 8px;
                font-size: 24px;
                display: block;
            }

        .body-text {
            margin-left: 350px;
            font-size: 18px;
        }

        table,
        th,
        td {
            padding: 10px;
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <div class="text-center">
            <a asp-controller="home" asp-action="">Home</a>
            <br />
            <a asp-controller="coursesearch" asp-action="">Course Search</a>
            <br />
            @{
                // TempData is global View Data is local
                var RoleIdentification = TempData["UserRoleAfterLogin"];
                if (RoleIdentification != null)
                {
                    if (RoleIdentification.ToString() == "Admin")
                    {
                        <a asp-controller="studentlist" asp-action="">Student List</a>
                        <br />
                        TempData["UserRoleAfterLogin"] = "Admin";
                    }
                }
            }
            <a asp-controller="login" asp-action="Logout">Logout</a>
        </div>
    </div>
    <div class="body-text">
        @RenderBody()
    </div>
</body>
</html>